icon: cog
label:
  de: Globale Einstellungen
  en: Global settings
columns:
  - width: 1/3
    sections:
      placeholder:
        headline: ''
        type: info
        text:
          de: Keine Einstellungen vorhanden.
          en: No settings available yet.
