title:
  de: Layout-Seite
  en: Layout page
image:
  icon: grid
  back: 'var(--theme-accent)'
  color: 'var(--theme-primary)'

tabs:
  content:
    label: Inhalt
    icon: text
    columns:
      - width: 3/4
        type: fields
        fields:
          blocks: fields/blocks
      - width: 1/4
        sections:
          headings:
            type: heading-structure
  seo: seo/page
