title:
  de: Alle Seiten
  en: All Pages

tabs:
  main:
    icon: page
    label:
      de: Navigation
      en: Navigation
    columns:
      - width: 2/3
        sections:
          pages:
            label:
              de: Seiten
              en: Pages
            type: pages
            info: '{{ page.url }}'
            create:
              - default
            templates:
              - default
            image: icon
      - width: 1/3
        sections:
          folders:
            label:
              de: Ordner
              en: Folders
            type: pages
            create: false
            templates:
              - assets
      - width: 1
        sections:
          info:
            label: ' '
            theme: none
            text:
              de: |
                **Ein Projekt von** [Tobias Möritz](https://moeritz.io)
                Fragen oder Probleme? (email: tobias@moeritz.io)
              en: |
                **A project by** [Tobias Möritz](https://moeritz.io)
                Questions or problems? (email: tobias@moeritz.io)
  global: sections/global-settings
  seo: seo/site
